server:
  port: 8881
spring:
  application:
    name: nacos-provider-888

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver